# ----------------------------
# Makefile Options
# ----------------------------

NAME = DEMO
ICON = icon.png
ARCHIVED = NO
DESCRIPTION = "tls_aes_encrypt test"
COMPRESSED = NO

CFLAGS = -Wall -Wextra -Oz -Isrc/include
CXXFLAGS = -Wall -Wextra -Oz -Isrc/include

# ----------------------------

HEADER_DIRS := src/include $(HEADER_DIRS)

include $(shell cedev-config --makefile)
