language: c
os: linux
sudo: false

matrix:
  include:
    - compiler: gcc-7
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - check
            - libsubunit-dev
            - gcc-7
      env:
        - LSAN_OPTIONS=verbosity=1:log_threads=1

    - compiler: clang-6.0
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-6.0
          packages:
            - check
            - libsubunit-dev
            - clang-6.0
      env:
        - LSAN_OPTIONS=verbosity=1:log_threads=1

addons:
  apt:
    packages:
      - check
      - cmake
      - libsubunit-dev

script: ./travis.sh
