# ----------------------------
# Makefile Options
# ----------------------------

NAME = DEMO
ICON = icon.png
ARCHIVED = NO
DESCRIPTION = "CE C Toolchain Demo"
COMPRESSED = NO

CFLAGS = -Wall -Wextra -Oz -I ../../src/include
CXXFLAGS = -Wall -Wextra -Oz -I ../../src/include

# ----------------------------

HEADER_DIRS := src/include/lwip

include $(shell cedev-config --makefile)
