name: Build lwIP-CE Project

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        language: [ 'cpp' ]

    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Fetch submodules
        run: git submodule update --init --recursive

      - name: Get repository information
        uses: actions/github-script@v6
        with:
          script: |
            const repo = context.payload.repository.full_name;
            console.log(`The repository is ${repo}`);
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y make tar

      - name: Download and extract CEdev
        run: |
          curl -sL github.com/CE-Programming/toolchain/releases/download/v11.2/CEdev-Linux.tar.gz | tar xz

      - name: Add CEdev to PATH
        run: |
          echo "CEdev/bin" >> $GITHUB_PATH
          echo $GITHUB_PATH

      - name: Make GFX
        run: make gfx

      # Initializes the CodeQL tools for scanning.
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}
        # If you wish to specify custom queries, you can do so here or in a config file.
        # By default, queries listed here will override any specified in a config file.
        # Prefix the list here with "+" to use these queries and those in the config file.

        # For more details on CodeQL's query packs, refer to: https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/configuring-code-scanning#using-queries-in-ql-packs
        # queries: security-extended,security-and-quality
          queries: security-and-quality
          build-mode: manual

        # build graphics, if applicable
      - name: Make GFX
        run: make gfx

        # build program
      - name: Make Build
        run: make

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:${{matrix.language}}"
          upload: false
        id: step1

      # Filter out rules with low severity or high false positve rate
      # Also filter out warnings in third-party code
      - name: Filter out unwanted errors and warnings
        uses: advanced-security/filter-sarif@v1
        with:
          patterns: |
            -**:cpp/path-injection
            -**:cpp/world-writable-file-creation
            -**:cpp/poorly-documented-function
            -**:cpp/potentially-dangerous-function
            -**:cpp/use-of-goto
            -**:cpp/integer-multiplication-cast-to-long
            -**:cpp/comparison-with-wider-type
            -**:cpp/leap-year/*
            -**:cpp/ambiguously-signed-bit-field
            -**:cpp/suspicious-pointer-scaling
            -**:cpp/suspicious-pointer-scaling-void
            -**:cpp/unsigned-comparison-zero
            -**/cmake*/Modules/**
          input: ${{ steps.step1.outputs.sarif-output }}/cpp.sarif
          output: ${{ steps.step1.outputs.sarif-output }}/cpp.sarif

      - name: Upload CodeQL results to code scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ steps.step1.outputs.sarif-output }}
          category: "/language:${{matrix.language}}"

      - name: Upload CodeQL results as an artifact
        if: success() || failure()
        uses: actions/upload-artifact@v3
        with:
          name: codeql-results
          path: ${{ steps.step1.outputs.sarif-output }}
          retention-days: 7

      - name: Upload bin directory
        uses: actions/upload-artifact@v3
        with:
          name: lwipce-demo
          path: bin/
