name: Build lwIP-CE Project

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Fetch submodules
        run: git submodule update --init --recursive

      - name: Get repository information
        uses: actions/github-script@v6
        with:
          script: |
            const repo = context.payload.repository.full_name;
            console.log(`The repository is ${repo}`);
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y make tar

      - name: Download and extract CEdev
        run: |
          curl -sL github.com/CE-Programming/toolchain/releases/download/v11.2/CEdev-Linux.tar.gz | tar xz

      - name: Add CEdev to PATH
        run: |
          echo "CEdev/bin" >> $GITHUB_PATH
          echo $GITHUB_PATH

      - name: Make GFX
        run: make gfx

      - name: Download CodeQL
        run: |
          curl -sL https://github.com/github/codeql-cli-binaries/releases/download/v2.17.6/codeql-linux64.zip | tar xz

      - name: Setting up CodeQL
        run: codeql/codeql database create lwip-ce-codeql --command=make --language=c-cpp

      - name: Scanning with CodeQL
        run: codeql/codeql database analyze lwip-ce-codeql --format=sarif-latest --output=analysis.sarif

      - name: Upload bin directory
        uses: actions/upload-artifact@v3
        with:
          name: bin-directory
          path: bin/

      - name: Upload CodeQL results as an artifact
        if: success() || failure()
        uses: actions/upload-artifact@v3
        with:
          name: analysis.sarif
          path: .
          retention-days: 7
